CI: Don't license check kernel config files
kata-containers/tests pull request #2962
Opened 2020-10-15 10:06 UTC by jodh-intel

Stop the license checker from looking for license headers in kernel config files.

Fixes: #2960.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

2020-10-15 10:07 UTC, jodh-intel commented
/test

2020-10-15 17:07 UTC, GabyCT approved these changes

2020-10-15 19:35 UTC, chavafg approved these changes

2020-10-15 20:42 UTC, egernst requested changes

2020-10-15 20:42 UTC, egernst commented on .ci/static-checks.sh
> +			--exclude="tools/packaging/kernel/configs" \
```suggestion
			--exclude="tools/packaging/kernel/configs/*" \
```

2020-10-16 08:34 UTC, jodh-intel commented on .ci/static-checks.sh
> +			--exclude="tools/packaging/kernel/configs" \
Good spot - updated!

2020-10-16 08:35 UTC, jodh-intel commented
/test

2020-10-16 16:06 UTC, egernst approved these changes

2020-10-16 16:06 UTC, merged