ci: Install ninja-build package on Ubuntu
kata-containers/tests pull request #3264
Opened 2021-02-19 13:57 UTC by wainersm

The ninja-build package is needed on Ubuntu for building QEMU 5.2
onward.

Fixes #3263

Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

2021-02-19 14:00 UTC, wainersm commented
/test

2021-02-19 16:57 UTC, GabyCT approved these changes

2021-02-22 08:54 UTC, fidencio reviewed
@wainersm, what's the ninja version needed?

I'm afraid the version present on ubuntu 18.04, that we run, may not be "new enough" for the QEMU needs.

2021-02-22 11:56 UTC, fidencio requested changes
So, taking a look at QEMU 5.2.0 (https://github.com/qemu/qemu/blob/553032db17440f8de011390e5a1cfddd13751b0b/meson.build#L1) we can see that the meson version required there is `0.55.0`, while the version Ubuntu 18.04 provides is `0.45.1`.

The first version of Ubuntu that supports the minimum meson version required by QEMU is 20.10, supporting `0.55.3`.

Please, refer to https://packages.ubuntu.com/search?keywords=meson for more information.


With everything above said, wouldn't be better / easier to rely on `pip` to install the latest version of the meson (or at least a specific version of that)?

2021-02-22 13:56 UTC, wainersm commented
@fidencio thanks for bringing this up, I really didn't pay attention to the version.

Now I double-checked to ensure this change is correct. Where are the facts:

* Ubuntu 18.04 provides ninja-build 1.8.2
```
root@d2cce3ba5230:/# lsb_release -r    
Release:	18.04
root@d2cce3ba5230:/# ninja --version
1.8.2
```
* Meson 0.55 requires ninja-build >= 1.7 (https://github.com/mesonbuild/meson/blob/0.55/README.md)
* Meson is a git submodule of QEMU (https://github.com/qemu/qemu/blob/master/.gitmodules#L61). So it can be consumed from sources, and in fact, we are not installing the packaged meson.

2021-02-22 15:33 UTC, fidencio approved these changes
@wainersm, thanks for double-checking and I didn't know QEMU was bundling `meson`.
lgtm, thanks!

2021-02-22 15:34 UTC, merged