ci: Allow use entry point for new VM.
kata-containers/tests pull request #3989
Opened 2021-09-20 19:13 UTC by jcvenegas

- Dont fail if test repository is already cloned
- Checkout to target branch only if provided

Signed-off-by: Carlos Venegas <jose.carlos.venegas.munoz@intel.com>

2021-09-20 19:36 UTC, jcvenegas commented
/test

2021-09-20 19:43 UTC, fidencio commented
/cc @wainersm

2021-09-20 19:44 UTC, fidencio commented
@jcvenegas, this is super cool and will make it easier for folks to run the CI locally. \o/

2021-09-21 09:41 UTC, Jakob-Naucke requested changes

2021-09-21 09:41 UTC, Jakob-Naucke commented on .ci/ci_entry_point.sh
> +                git rebase "origin/${ghprbTargetBranch}"
please use tabs here, LGTM otherwise

2021-09-21 13:14 UTC, wainersm commented
@jcvenegas very interesting changes! I never tried to run that script (consequently `jenkins_job_build.sh`) from outside of Jenkins. With those changes it does work fine?

2021-09-21 15:14 UTC, GabyCT commented
lgtm, just applied the changes requested thanks

2021-09-21 15:29 UTC, wainersm approved these changes
Thanks @jcvenegas !

2021-09-21 17:24 UTC, jcvenegas commented on .ci/ci_entry_point.sh
> +mkdir -p "$(dirname ${tests_repo_dir})"
nice, fixed

2021-09-21 17:25 UTC, jcvenegas commented
/test

2021-09-23 14:42 UTC, jcvenegas commented
/test

2021-09-27 04:55 UTC, jcvenegas commented
/test

2021-09-27 06:19 UTC, jcvenegas commented
hi @Jakob-Naucke , could you take a look again?

2021-09-27 08:44 UTC, Jakob-Naucke approved these changes
@jcvenegas yes, sorry, only TIL the "Request changes" thing blocked approved PRs.

2021-09-27 08:44 UTC, merged