runtime-rs: add upcall kernel patch into CI
kata-containers/tests pull request #5294
Opened 2022-12-01 10:10 UTC by studychao

upcall is a must feature for Dragonball to enable device hotplug, so in CI system we will add upcall patches into build kernel process to let Dragonball use the guest kernel with upcall server.

Depends-on: github.com/kata-containers/kata-containers#5712 

fixes: #5293

Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>

2022-12-09 10:04 UTC, fidencio approved these changes
lgtm, thanks @studychao!

2022-12-09 10:04 UTC, fidencio commented
/test

2022-12-15 08:31 UTC, liubin approved these changes

2022-12-15 08:34 UTC, liubin commented
/test-dragonball

2022-12-15 13:45 UTC, liubin requested changes
```diff
- 			install_kernel "${kernel_type}" $(get_version "assets.kernel.dragonball-kernel-experimental.version")
+ 			install_kernel "${kernel_type}" $(get_version "assets.dragonball-kernel-experimental.version")
```

2022-12-15 16:26 UTC, studychao commented
> ```diff
> - install_kernel "${kernel_type}" $(get_version "assets.kernel.dragonball-kernel-experimental.version")
> + install_kernel "${kernel_type}" $(get_version "assets.dragonball-kernel-experimental.version")
> ```

Wow thanks for pointing out this detail. 
Already changed.

2022-12-16 02:50 UTC, liubin approved these changes

2022-12-16 02:50 UTC, merged