metrics: Enable new CI metrics baremetal.
kata-containers/tests pull request #5402
Opened 2023-01-20 22:38 UTC by GabyCT

This PR enables a new CI metrics baremetal.

Fixes #5401

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

2023-01-20 22:39 UTC, GabyCT commented
/test-newmetrics

2023-01-23 16:09 UTC, GabyCT commented
/test-newmetrics

2023-01-23 16:34 UTC, GabyCT commented
/test-newmetrics

2023-01-23 17:14 UTC, GabyCT commented
/test-newmetrics

2023-01-23 17:50 UTC, GabyCT commented
/test-newmetrics

2023-01-23 18:08 UTC, GabyCT commented
/test-newmetrics

2023-01-23 19:13 UTC, GabyCT commented
/test-newmetrics

2023-01-23 19:45 UTC, GabyCT commented
/test-newmetrics

2023-01-23 20:14 UTC, GabyCT commented
/test-newmetrics

2023-01-23 20:47 UTC, GabyCT commented
/test-newmetrics

2023-01-23 21:28 UTC, GabyCT commented
/test-newmetrics

2023-01-23 22:12 UTC, GabyCT commented
/test-newmetrics

2023-01-23 22:43 UTC, GabyCT commented
/test-newmetrics

2023-01-23 23:11 UTC, GabyCT commented
/test

2023-01-24 15:33 UTC, GabyCT commented
/test-newmetrics

2023-01-24 15:50 UTC, dborquez commented on .ci/setup_env_ubuntu.sh
>  echo "Update apt repositories"
Thanks @GabyCT,  could you please comment this line to be consistent with the next commented line.

2023-01-24 15:52 UTC, dborquez requested changes
thanks @GabyCT LGTM, just resolve the suggestion made

2023-01-24 16:21 UTC, GabyCT commented
@dborquez changes applied, thanks

2023-01-24 16:23 UTC, GabyCT commented
/test-newvfio

2023-01-24 16:30 UTC, dborquez approved these changes

2023-01-24 16:45 UTC, chavafg approved these changes

2023-01-24 17:02 UTC, GabyCT commented
/test-vfio

2023-01-24 17:06 UTC, GabyCT commented
/test-new-metrics

2023-01-24 19:01 UTC, GabyCT commented
/test-fc

2023-01-24 19:37 UTC, merged