Remove stale coco artifacts
kata-containers/tests pull request #5503
Opened 2023-03-01 20:52 UTC by UnmeshDeodhar

Remove coco artifacts.

Fixes: #5502

Signed-of-by: Unmesh Deodhar <udeodhar@amd.com>

2023-03-01 22:20 UTC, UnmeshDeodhar commented
/test

2023-03-02 09:09 UTC, fidencio commented
This works well, but I think we should also remove some links we create during the installation.
For instance, if you go to the install scripts, you'll notice we end up linking to binaries / ovmf / and whatnot to /usr/local/bin.  Please, take a look at those scripts and also clean up the scripts we create there.

2023-03-03 17:39 UTC, UnmeshDeodhar commented
/test

2023-03-03 18:54 UTC, UnmeshDeodhar commented
/test

2023-03-06 17:48 UTC, UnmeshDeodhar commented
@fidencio I have added the changes that delete and unlink binaries from /opt/confidential-containers please let me know if this looks okay.

2023-03-06 19:09 UTC, fidencio requested changes
I've left a few comments.

2023-03-06 19:09 UTC, fidencio commented on .ci/lib.sh
> +	sudo rm -rf /opt/confidential-containers
So, here you removed everything from `/opt/confidential-containers` ...

2023-03-06 19:09 UTC, fidencio commented on .ci/lib.sh
> +	unlink /opt/confidential-containers/share/ovmf
... and then here you're trying to unlink a dir that was just removed in a few lines above.

As this pattern repeats in all the removals, so I'd suggest to move the `sudo rm -rf /opt/confidential-containers` to be the last part of the cleanup.

2023-03-06 19:09 UTC, fidencio commented on .ci/lib.sh
> +	sudo rm -f /usr/bin/qemu-system-x86_64
You're missing:
*  `./opt/confidential-containers/bin/qemu-system-x86_64-tdx` which seems to be linked as `/usr/bin/qemu-system-x86_64-tdx`
* `/opt/kata/libexec/virtiofsd`, which is linked as `/usr/libexec/virtiofsd`
`

2023-03-06 19:27 UTC, fidencio approved these changes
lgtm, thanks @UnmeshDeodhar!

2023-03-06 19:28 UTC, fidencio commented
/test

2023-03-06 19:28 UTC, UnmeshDeodhar commented
/test

2023-03-06 20:46 UTC, fidencio commented
Cloud Hypervisor TDX is green but didn't report back: http://10.112.240.208:8080/job/tests-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/374/console

2023-03-06 21:04 UTC, merged